### ISSUE TITLE
Support Lokomotive on managed platforms

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#215]
We should support Lokomotive on managed platforms like AKS, EKS, and GKE.

This would include:

- [ ] Having lokoctl spin up a managed cluster and install components on it
     - [x] AKS (https://github.com/kinvolk/lokomotive/issues/216)
     - [ ] EKS
     - [ ] GKE
- [x] Installing components on existing managed clusters
   - This should pretty much already work

**Comment by iaguis** [comment]
I'm splitting this on separate issues for better tracking.

https://github.com/kinvolk/lokomotive/issues/549
https://github.com/kinvolk/lokomotive/issues/549
