### ISSUE TITLE
Improve Lokomotive User Experience

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#319]
Umbrella issue for initial Lokomotive UX improvements:

- [ ] Make quickstarts quicker (https://github.com/kinvolk/lokomotive/issues/273)
- [ ] Simplify sample configs in quickstart guides (https://github.com/kinvolk/lokomotive/issues/244)
- [ ] Improve terraform related UX (https://github.com/kinvolk/lokomotive/issues/225)
- [ ] Include a demo GIF in the README (https://github.com/kinvolk/lokomotive/issues/318)
